/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salry;

import javax.swing.JOptionPane;

/**
 *
 * @author vincent ososi
 */
public class PoshoMillWorks extends javax.swing.JFrame {

    /**
     * Creates new form PoshoMillWorks
     */
    public PoshoMillWorks() {
        initComponents();
        ClearValues();
        setResizable(false);
        setTitle("Easy Poshomill");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabelCahin = new javax.swing.JLabel();
        jLabelCashout = new javax.swing.JLabel();
        jLabelpreviousunits = new javax.swing.JLabel();
        jLabelPower = new javax.swing.JLabel();
        jLabelpower = new javax.swing.JLabel();
        jLabelProfit = new javax.swing.JLabel();
        jLabelLoss = new javax.swing.JLabel();
        jLabelSalary = new javax.swing.JLabel();
        jLabelCashExpected = new javax.swing.JLabel();
        jButtonClearValues = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jTextFieldCashin = new javax.swing.JTextField();
        jTextFieldCashout = new javax.swing.JTextField();
        jTextFieldpreviousunits = new javax.swing.JTextField();
        jTextFieldBalance = new javax.swing.JTextField();
        jTextFieldpower = new javax.swing.JTextField();
        jTextFieldprofit = new javax.swing.JTextField();
        jTextFieldloss = new javax.swing.JTextField();
        jTextFieldsalary = new javax.swing.JTextField();
        jTextFieldcashexpected = new javax.swing.JTextField();
        jLabelnewunits = new javax.swing.JLabel();
        jTextFieldnewunits = new javax.swing.JTextField();
        jLabelunitsused = new javax.swing.JLabel();
        jTextFieldunitsusedup = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldmachinerepair = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldservices = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFielddepreciation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldothers = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldnightunits = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldpaymentovernight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldusikuunits = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POSHOMILL");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.blue);

        jLabelCahin.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelCahin.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCahin.setText("Cash in");

        jLabelCashout.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelCashout.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCashout.setText("Cash out");

        jLabelpreviousunits.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelpreviousunits.setForeground(new java.awt.Color(153, 51, 255));
        jLabelpreviousunits.setText("Previous Units");

        jLabelPower.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelPower.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPower.setText("Balance");

        jLabelpower.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelpower.setForeground(new java.awt.Color(153, 51, 255));
        jLabelpower.setText("Power Payement");

        jLabelProfit.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelProfit.setForeground(new java.awt.Color(0, 0, 0));
        jLabelProfit.setText("Profit/Savings");

        jLabelLoss.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelLoss.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLoss.setText("Loss");

        jLabelSalary.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelSalary.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalary.setText("Salary");

        jLabelCashExpected.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelCashExpected.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCashExpected.setText("Total Cash Expected In");

        jButtonClearValues.setBackground(new java.awt.Color(255, 153, 0));
        jButtonClearValues.setForeground(new java.awt.Color(0, 0, 255));
        jButtonClearValues.setText("Clear Values To Input Others");
        jButtonClearValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearValuesActionPerformed(evt);
            }
        });

        jButtonCalculate.setBackground(new java.awt.Color(0, 0, 255));
        jButtonCalculate.setForeground(new java.awt.Color(255, 153, 0));
        jButtonCalculate.setText("Caculate All Your Entries");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });

        jTextFieldCashin.setText("0.00");
        jTextFieldCashin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCashinActionPerformed(evt);
            }
        });

        jTextFieldCashout.setText("0.00");

        jTextFieldpreviousunits.setText("0.00");
        jTextFieldpreviousunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpreviousunitsActionPerformed(evt);
            }
        });

        jTextFieldBalance.setText("0.00");

        jTextFieldpower.setText("0.00");
        jTextFieldpower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpowerActionPerformed(evt);
            }
        });

        jTextFieldprofit.setText("0.00");

        jTextFieldloss.setText("0.00");

        jTextFieldsalary.setText("0.00");

        jTextFieldcashexpected.setText("0.00");

        jLabelnewunits.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelnewunits.setForeground(new java.awt.Color(153, 51, 255));
        jLabelnewunits.setText("New Units");

        jTextFieldnewunits.setText("0.00");

        jLabelunitsused.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabelunitsused.setForeground(new java.awt.Color(153, 51, 255));
        jLabelunitsused.setText("Total Units Used Up(KWh)");

        jTextFieldunitsusedup.setText("0.00");
        jTextFieldunitsusedup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldunitsusedupActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Machine repair");

        jTextFieldmachinerepair.setText("0.00");
        jTextFieldmachinerepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmachinerepairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Services");

        jTextFieldservices.setText("0.00");
        jTextFieldservices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldservicesActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Machine depreciation");

        jTextFielddepreciation.setText("0.00");

        jLabel5.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Others(machinerepair,services,depreciation)");

        jTextFieldothers.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 51, 255));
        jLabel6.setText("Total Units Used Overnight(KWh)");

        jTextFieldnightunits.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 51, 255));
        jLabel8.setText("Power payment overnight");

        jTextFieldpaymentovernight.setText("0.00");
        jTextFieldpaymentovernight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpaymentovernightActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 51, 255));
        jLabel9.setText("NightUnits");

        jTextFieldusikuunits.setText("0.00");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Felix Titling", 3, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("   POSHOMILL WORKS AND MANAGEMENT TO GET EFFICIECY AND TRANSPARENCE");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salry/next3.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salry/next3.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salry/next3.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salry/visiososi.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Copyright of Visiososi_Enterprise.");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salry/savings.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Algerian", 0, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Save Today Save Tomorrow.");

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("EASYPOSHOMILL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCashout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCahin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelpreviousunits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelnewunits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldCashin)
                                            .addComponent(jTextFieldCashout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelProfit)
                                            .addComponent(jLabelSalary))
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldprofit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelCashExpected)
                                                .addGap(38, 38, 38))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelLoss)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldloss, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabelPower)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldcashexpected, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldpreviousunits, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                        .addComponent(jLabelpower)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldpower, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelunitsused)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldunitsusedup, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldservices, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldmachinerepair, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldusikuunits, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldnewunits, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFielddepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldpaymentovernight, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldnightunits, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldothers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonCalculate)
                                    .addComponent(jButtonClearValues))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(412, 412, 412))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldCashin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCahin)
                                        .addComponent(jLabelLoss)
                                        .addComponent(jTextFieldloss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelPower)
                                        .addComponent(jTextFieldsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelSalary)))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCashout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCashout)
                                    .addComponent(jLabelProfit)
                                    .addComponent(jTextFieldprofit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldcashexpected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCashExpected, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldpreviousunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpreviousunits)
                            .addComponent(jLabelunitsused)
                            .addComponent(jTextFieldunitsusedup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelpower)
                            .addComponent(jTextFieldpower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldnewunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelnewunits)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldnightunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldusikuunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldpaymentovernight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldservices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(jTextFielddepreciation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldmachinerepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonClearValues, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldpreviousunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpreviousunitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpreviousunitsActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        try {
            double units, cashin, cashout, profit, loss, cashexpd, salary, power, balance, prvunits, newunits,
                    machinerepair, retal, services, depreciation, others, nightunits, powernight, night;
            prvunits = Double.parseDouble(this.jTextFieldpreviousunits.getText());
            newunits = Double.parseDouble(this.jTextFieldnewunits.getText());
            cashin = Double.parseDouble(this.jTextFieldCashin.getText());
            cashout = Double.parseDouble(this.jTextFieldCashout.getText());
            machinerepair = Double.parseDouble(this.jTextFieldmachinerepair.getText());
            services = Double.parseDouble(this.jTextFieldservices.getText());
            depreciation = Double.parseDouble(this.jTextFielddepreciation.getText());
            night = Double.parseDouble(this.jTextFieldusikuunits.getText());
            int k = 85;
            units = newunits - prvunits;
            cashexpd = (k * units);
            this.jTextFieldcashexpected.setText(String.format("%.2f", cashexpd));
            jTextFieldcashexpected.setToolTipText("Total cash expected for the used up units");
            this.jTextFieldunitsusedup.setText(String.format("%.2f", units));
            balance = (cashin - cashout);
            this.jTextFieldBalance.setText(String.format("%.2f", balance));
            nightunits = (prvunits - night);
            this.jTextFieldnightunits.setText(String.format("%.2f", nightunits));
            double rate = 0.08;
            salary = rate * cashin;
            this.jTextFieldsalary.setText(String.format("%.2f", salary));
            loss = (cashexpd - cashin);
            this.jTextFieldloss.setText(String.format("%.2f", loss));
            powernight = (nightunits * 16.62);
            this.jTextFieldpaymentovernight.setText(String.format("%.2f", powernight));
            double powerrate = 16.62;
            power = (powerrate * units);
            this.jTextFieldpower.setText(String.format("%.2f", power));
            others = (machinerepair + services + depreciation);
            this.jTextFieldothers.setText(String.format("%.2f", others));
            profit = (balance - power) - (salary) - (others);
            this.jTextFieldprofit.setText(String.format("%.2f", profit));
        } catch (Exception err) {
            JOptionPane.showMessageDialog(rootPane, "Please enter values");
        }
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jTextFieldCashinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCashinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCashinActionPerformed
    private void ClearValues() {
        this.jTextFieldpower.setText(String.format(""));
        this.jTextFieldBalance.setText(String.format(""));
        this.jTextFieldCashin.setText(String.format(""));
        this.jTextFieldCashout.setText(String.format(""));
        this.jTextFieldcashexpected.setText(String.format(""));
        this.jTextFieldloss.setText(String.format(""));
        this.jTextFieldnewunits.setText(String.format(""));
        this.jTextFieldpreviousunits.setText(String.format(""));
        this.jTextFieldprofit.setText(String.format(""));
        this.jTextFieldsalary.setText(String.format(""));
        this.jTextFieldunitsusedup.setText(String.format(""));
        this.jTextFielddepreciation.setText(String.format(""));
        this.jTextFieldmachinerepair.setText(String.format(""));
        this.jTextFieldothers.setText(String.format(""));
        this.jTextFieldservices.setText(String.format(""));
        this.jTextFieldnightunits.setText(String.format(""));
        this.jTextFieldpaymentovernight.setText(String.format(""));
        this.jTextFieldusikuunits.setText(String.format(""));
    }
    private void jButtonClearValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearValuesActionPerformed
        ClearValues();
    }//GEN-LAST:event_jButtonClearValuesActionPerformed

    private void jTextFieldmachinerepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmachinerepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmachinerepairActionPerformed

    private void jTextFieldpaymentovernightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpaymentovernightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpaymentovernightActionPerformed

    private void jTextFieldpowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpowerActionPerformed

    private void jTextFieldunitsusedupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldunitsusedupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldunitsusedupActionPerformed

    private void jTextFieldservicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldservicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldservicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(PoshoMillWorks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(PoshoMillWorks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(PoshoMillWorks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(PoshoMillWorks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

            /* Create and display the form */
           
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoshoLogin().setVisible(true);
            }
        });
        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, "An err occured");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonClearValues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCahin;
    private javax.swing.JLabel jLabelCashExpected;
    private javax.swing.JLabel jLabelCashout;
    private javax.swing.JLabel jLabelLoss;
    private javax.swing.JLabel jLabelPower;
    private javax.swing.JLabel jLabelProfit;
    private javax.swing.JLabel jLabelSalary;
    private javax.swing.JLabel jLabelnewunits;
    private javax.swing.JLabel jLabelpower;
    private javax.swing.JLabel jLabelpreviousunits;
    private javax.swing.JLabel jLabelunitsused;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextFieldBalance;
    private javax.swing.JTextField jTextFieldCashin;
    private javax.swing.JTextField jTextFieldCashout;
    private javax.swing.JTextField jTextFieldcashexpected;
    private javax.swing.JTextField jTextFielddepreciation;
    private javax.swing.JTextField jTextFieldloss;
    private javax.swing.JTextField jTextFieldmachinerepair;
    private javax.swing.JTextField jTextFieldnewunits;
    private javax.swing.JTextField jTextFieldnightunits;
    private javax.swing.JTextField jTextFieldothers;
    private javax.swing.JTextField jTextFieldpaymentovernight;
    private javax.swing.JTextField jTextFieldpower;
    private javax.swing.JTextField jTextFieldpreviousunits;
    private javax.swing.JTextField jTextFieldprofit;
    private javax.swing.JTextField jTextFieldsalary;
    private javax.swing.JTextField jTextFieldservices;
    private javax.swing.JTextField jTextFieldunitsusedup;
    private javax.swing.JTextField jTextFieldusikuunits;
    // End of variables declaration//GEN-END:variables
}
